# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Keri Jacobs
tagline:          'A Jekyll theme'
description:      '<p>Iowa Institute for Cooperatives Economics Professor Assistant Professor</p> <p>Department of Economics Cooperatives Extension Specialist</p>'
email: 			  'kljacobs@iastate.edu'
url:              http://bradybeck.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
