# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Temporary Home
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

about:
  - title: Faith.
    description: I love Jesus. I listen to a lot of podcasts and read a lot of articles.
    icon: 'fa-plus'
    url: '/'
  - title: Tech.
    description: It's about to get nerdy. I'm a software engineer, If there's something sweet I'm working on or an advancement in tech that catches my eye I'll throw it up here.
    icon: 'fa-desktop'
    url: '/'
  - title: Articles.
    description: Here you'll find things that I'm reading or current events that I think are worth while for eyes other than my own. Mostly it'll just be the link but sometimes if you're lucky I'll share a few thoughts.
    icon: 'fa-link'
    url: '/articles/'
  - title: Projects.
    description: The wife keeps me busy doing all sorts of things. So I'll share what we've been up to with lots of pictures.
    icon: 'fa-briefcase'
    url: '/'


# Build settings
markdown: kramdown
